[func_args.assertion.1] line 10 assertion : SUCCESS
[func_args.assertion.2] line 11 assertion : FAILURE
VERIFICATION FAILED
